import { fromObjectPolar as fromPolar, toObjectPolar as toPolar } from './conversion/index'
import {
  addObject as add,
  addObjectScalar as addScalar,
  addObjectScalarX as addScalarX,
  addObjectScalarY as addScalarY,
  addObjectX as addX,
  addObjectY as addY,
  ceilObject as ceil,
  clampObject as clamp,
  divideObject as divide,
  divideObjectScalar as divideScalar,
  divideObjectScalarX as divideScalarX,
  divideObjectScalarY as divideScalarY,
  divideObjectX as divideX,
  divideObjectY as divideY,
  floorObject as floor,
  fractObject as fract,
  invertObject as invert,
  invertObjectX as invertX,
  invertObjectY as invertY,
  lerpObject as lerp,
  multiplyObject as multiply,
  multiplyObjectScalar as multiplyScalar,
  multiplyObjectScalarX as multiplyScalarX,
  multiplyObjectScalarY as multiplyScalarY,
  multiplyObjectX as multiplyX,
  multiplyObjectY as multiplyY,
  negateObject as negate,
  negateObjectX as negateX,
  negateObjectY as negateY,
  normizeObject as normize,
  roundObject as round,
  subtractObject as subtract,
  subtractObjectScalar as subtractScalar,
  subtractObjectScalarX as subtractScalarX,
  subtractObjectScalarY as subtractScalarY,
  subtractObjectX as subtractX,
  subtractObjectY as subtractY,
  unitObject as unit,
} from './operation/index'
import {
  angleObject as angle,
  angleObjectDegrees as angleDegrees,
  crossObject as cross,
  directionObject as direction,
  distanceObject as distance,
  distanceObjectX as distanceX,
  distanceObjectY as distanceY,
  dotObject as dot,
  horizontalAngleDegreesObject as horizontalAngleDegrees,
  horizontalAngleObject as horizontalAngle,
  lengthObject as length,
  magnitudeObject as magnitude,
  normObject as norm,
  verticalAngleDegreesObject as verticalAngleDegrees,
  verticalAngleObject as verticalAngle,
} from './product/index'

// eslint-disable-next-line @typescript-eslint/no-namespace
export {
  add,
  addScalar,
  addScalarX,
  addScalarY,
  addX,
  addY,
  angle,
  angleDegrees,
  ceil,
  clamp,
  cross,
  direction,
  distance,
  distanceX,
  distanceY,
  divide,
  divideScalar,
  divideScalarX,
  divideScalarY,
  divideX,
  divideY,
  dot,
  floor,
  fract,
  fromPolar,
  horizontalAngle,
  horizontalAngleDegrees,
  invert,
  invertX,
  invertY,
  length,
  lerp,
  magnitude,
  multiply,
  multiplyScalar,
  multiplyScalarX,
  multiplyScalarY,
  multiplyX,
  multiplyY,
  negate,
  negateX,
  negateY,
  norm,
  normize,
  round,
  subtract,
  subtractScalar,
  subtractScalarX,
  subtractScalarY,
  subtractX,
  subtractY,
  toPolar,
  unit,
  verticalAngle,
  verticalAngleDegrees,
}
