import { fromArrayPolar as fromPolar, toArrayPolar as toPolar } from './conversion/index'
import {
  addArray as add,
  addArrayScalar as addScalar,
  addArrayScalarX as addScalarX,
  addArrayScalarY as addScalarY,
  addArrayX as addX,
  addArrayY as addY,
  ceilArray as ceil,
  clampArray as clamp,
  divideArray as divide,
  divideArrayScalar as divideScalar,
  divideArrayScalarX as divideScalarX,
  divideArrayScalarY as divideScalarY,
  divideArrayX as divideX,
  divideArrayY as divideY,
  floorArray as floor,
  fractArray as fract,
  invertArray as invert,
  invertArrayX as invertX,
  invertArrayY as invertY,
  lerpArray as lerp,
  multiplyArray as multiply,
  multiplyArrayScalar as multiplyScalar,
  multiplyArrayScalarX as multiplyScalarX,
  multiplyArrayScalarY as multiplyScalarY,
  multiplyArrayX as multiplyX,
  multiplyArrayY as multiplyY,
  negateArray as negate,
  negateArrayX as negateX,
  negateArrayY as negateY,
  normizeArray as normize,
  roundArray as round,
  subtractArray as subtract,
  subtractArrayScalar as subtractScalar,
  subtractArrayScalarX as subtractScalarX,
  subtractArrayScalarY as subtractScalarY,
  subtractArrayX as subtractX,
  subtractArrayY as subtractY,
  unitArray as unit,
} from './operation/index'
import {
  angleArray as angle,
  angleArrayDegrees as angleDegrees,
  crossArray as cross,
  directionArray as direction,
  distanceArray as distance,
  distanceArrayX as distanceX,
  distanceArrayY as distanceY,
  dotArray as dot,
  horizontalAngleDegreesArray as horizontalAngleDegrees,
  horizontalAngleArray as horizontalAngle,
  lengthArray as length,
  magnitudeArray as magnitude,
  normArray as norm,
  verticalAngleDegreesArray as verticalAngleDegrees,
  verticalAngleArray as verticalAngle,
} from './product/index'

// eslint-disable-next-line @typescript-eslint/no-namespace
export {
  add,
  addScalar,
  addScalarX,
  addScalarY,
  addX,
  addY,
  angle,
  angleDegrees,
  ceil,
  clamp,
  cross,
  direction,
  distance,
  distanceX,
  distanceY,
  divide,
  divideScalar,
  divideScalarX,
  divideScalarY,
  divideX,
  divideY,
  dot,
  floor,
  fract,
  fromPolar,
  horizontalAngle,
  horizontalAngleDegrees,
  invert,
  invertX,
  invertY,
  length,
  lerp,
  magnitude,
  multiply,
  multiplyScalar,
  multiplyScalarX,
  multiplyScalarY,
  multiplyX,
  multiplyY,
  negate,
  negateX,
  negateY,
  norm,
  normize,
  round,
  subtract,
  subtractScalar,
  subtractScalarX,
  subtractScalarY,
  subtractX,
  subtractY,
  toPolar,
  unit,
  verticalAngle,
  verticalAngleDegrees,
}
